/* Resursfillabels f”r SET_NVM */

#define NVM_MAIN 0   /* Formul„r/Dialog */
#define R_SWED   4   /* BUTTON i tr„d NVM_MAIN */
#define R_ENG    5   /* BUTTON i tr„d NVM_MAIN */
#define R_TLANG  6   /* STRING i tr„d NVM_MAIN */
#define R_LANG   7   /* BUTTON i tr„d NVM_MAIN */
#define R_LANGB  8   /* BUTTON i tr„d NVM_MAIN */
#define R_TTANG  9   /* STRING i tr„d NVM_MAIN */
#define R_TANG   10  /* BUTTON i tr„d NVM_MAIN */
#define R_TANGB  11  /* BUTTON i tr„d NVM_MAIN */
#define R_TUR    12  /* STRING i tr„d NVM_MAIN */
#define R_UR     13  /* BUTTON i tr„d NVM_MAIN */
#define R_TDATE  14  /* STRING i tr„d NVM_MAIN */
#define R_DATE   15  /* BUTTON i tr„d NVM_MAIN */
#define R_SKILJ  16  /* FTEXT i tr„d NVM_MAIN */
#define R_INSTALL 17  /* BUTTON i tr„d NVM_MAIN */
#define R_AVBRYT 18  /* BUTTON i tr„d NVM_MAIN */

#define NVM_SUBS 1   /* Formul„r/Dialog */
#define S_MAIN   0   /* BOX i tr„d NVM_SUBS */
#define S_DESKTOP 1   /* BOX i tr„d NVM_SUBS */
#define S_TANGENT 17  /* BOX i tr„d NVM_SUBS */
#define S_UR     33  /* BOX i tr„d NVM_SUBS */
#define S_DATUM  36  /* BOX i tr„d NVM_SUBS */
